import { useEffect, useState } from "react";
import AppLink from "../components/AppLink";
import MetricCard from "../components/MetricCard";
import { request } from "../services/api";

export default function DashboardPage({ session, onLogout }) {
  const [stats, setStats] = useState(null); const [logs, setLogs] = useState([]); const [services, setServices] = useState([]); const [filters, setFilters] = useState({ start: "", end: "", service: "" }); const [collapsed, setCollapsed] = useState(false); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)).toString();
  async function loadDashboard() { try { const [nextStats, checks] = await Promise.all([request(`/stats?${query}`, {}, session.token), request(`/checks?${query}`, {}, session.token)]); setStats(nextStats); setLogs(checks.items); setServices(checks.services); } catch (requestError) { setMessage(requestError.message); if (requestError.message === "Authentication required") onLogout(); } }
  useEffect(() => { loadDashboard(); }, [session.token, query]);
  async function upload(file) { setLoading(true); setMessage(""); try { const bytes = new Uint8Array(await file.arrayBuffer()); const content = String.fromCharCode(...bytes); const result = await request("/uploads", { method: "POST", body: JSON.stringify({ filename: file.name, csvBase64: btoa(content) }) }, session.token); setMessage(`Imported ${result.acceptedRows}/${result.totalRows} records. Rejected: ${result.rejectedRows}. ${Object.entries(result.rejectionReasons).map(([key, value]) => `${key}: ${value}`).join(", ")}`); loadDashboard(); } catch (requestError) { setMessage(requestError.message); } finally { setLoading(false); } }
  return <main><header><div><p className="eyebrow">HEALTHCHECK OPS</p><h1>Service reliability</h1></div><div className="headerActions">{session.user?.role === "admin" && <><AppLink className="button" href="/admin/register">Register viewer</AppLink><AppLink className="ghost navLink" href="/admin/data">Manage data</AppLink><label className="button">{loading ? "Importing…" : "Upload CSV"}<input type="file" accept=".csv,text/csv" hidden disabled={loading} onChange={(event) => event.target.files[0] && upload(event.target.files[0])} /></label></>}<button className="ghost" onClick={onLogout}>Sign out</button></div></header>{message && <p className="notice">{message}</p>}<section className="panel"><div className="panelHead"><div><h2>Operational snapshot</h2><span>Calculated from the selected monitoring period</span></div><button className="ghost" onClick={() => setCollapsed(!collapsed)}>{collapsed ? "Expand" : "Collapse"}</button></div>{!collapsed && <><div className="cards"><MetricCard label="Availability" value={`${stats?.availability ?? 0}%`} tone="good" /><MetricCard label="Failed checks" value={stats?.failures ?? 0} tone="bad" /><MetricCard label="Average latency" value={`${stats?.avgLatency ?? 0} ms`} /><MetricCard label="P95 latency" value={`${stats?.p95 ?? 0} ms`} /><MetricCard label="Total checks" value={stats?.total ?? 0} /></div><div className="serviceList">{stats?.services.map((item) => <div key={item._id}><strong>{item._id}</strong><span>{item.checks - item.failures}/{item.checks} successful · {Math.round(item.avgLatency)} ms avg</span></div>)}</div></>}</section><section className="panel"><div className="panelHead"><div><h2>Check logs</h2><span>{logs.length} most recent matching records</span></div></div><div className="filters"><label>From<input type="date" value={filters.start} onChange={(event) => setFilters({ ...filters, start: event.target.value })} /></label><label>To<input type="date" value={filters.end} onChange={(event) => setFilters({ ...filters, end: event.target.value })} /></label><label>Service<select value={filters.service} onChange={(event) => setFilters({ ...filters, service: event.target.value })}><option value="">All services</option>{services.map((item) => <option key={item}>{item}</option>)}</select></label><button className="ghost" onClick={() => setFilters({ start: "", end: "", service: "" })}>Clear</button></div><div className="tableWrap"><table><thead><tr><th>Timestamp</th><th>Service</th><th>Status</th><th>Latency</th><th>Agent / region</th></tr></thead><tbody>{logs.map((item) => <tr key={item._id}><td>{new Date(item.checkedAt).toLocaleString()}</td><td>{item.service}</td><td><span className={item.statusCode >= 400 ? "status bad" : "status good"}>{item.statusCode}</span></td><td>{item.latencyMs} ms</td><td>{item.agent} / {item.region}</td></tr>)}{!logs.length && <tr><td colSpan="5" className="empty">No monitoring checks match this filter.</td></tr>}</tbody></table></div></section></main>;
}
